name = "REoptPlots"
uuid = "81d7bfe7-808b-4a8e-bf67-c3577adb378e"
authors = ["Nick Laws <nick.laws@nrel.gov>"]
version = "0.1.1"

[deps]
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
REopt = "d36ad4e8-d74a-4f7a-ace1-eaea049febf6"

[compat]
PlotlyJS = "0.18"
REopt = "0.13"
julia = "1.7"